In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load dataset
df = pd.read_csv(r'synthetic_credit_card_approval.csv')
df.head()

,Num_Children,Group,Income,Own_Car,Own_Housing,Target
0,4,0,36151,0,0,0
1,0,0,36095,1,0,0
2,2,1,62110,1,1,0
3,0,1,73644,1,0,0
4,3,0,99146,0,0,1


In [2]:
# Basic info
print('Shape:', df.shape)
print('\nColumns:\n', df.columns)
print('\nInfo:')
df.info()

print('\nMissing values per column:')
print(df.isnull().sum())

Shape: (500000, 6)

Columns:
 Index(['Num_Children', 'Group', 'Income', 'Own_Car', 'Own_Housing', 'Target'], dtype='object')

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Num_Children  500000 non-null  int64
 1   Group         500000 non-null  int64
 2   Income        500000 non-null  int64
 3   Own_Car       500000 non-null  int64
 4   Own_Housing   500000 non-null  int64
 5   Target        500000 non-null  int64
dtypes: int64(6)
memory usage: 22.9 MB

Missing values per column:
Num_Children    0
Group           0
Income          0
Own_Car         0
Own_Housing     0
Target          0
dtype: int64


In [3]:
# Preprocessing: Encode categorical columns and scale numeric features
from sklearn.compose import ColumnTransformer

# Drop duplicates
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f'Dropped {before-after} duplicate rows')

cat_cols = df.select_dtypes(include=['object']).columns.tolist()
print('Categorical columns:', cat_cols)
le = LabelEncoder()
for col in cat_cols:
    try:
        df[col] = le.fit_transform(df[col].astype(str))
    except Exception as e:
        print('Could not encode', col, e)

# Determine target column
possible_targets = ['target', 'approved', 'approval', 'y', 'label']
for t in possible_targets:
    if t in df.columns:
        target_col = t
        break
else:
    target_col = df.columns[-1]

print('Using target column:', target_col)
X = df.drop(columns=[target_col])
y = df[target_col]

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print('Feature matrix shape:', X_scaled.shape)
print('Target distribution:\n', y.value_counts())

Dropped 49202 duplicate rows
Categorical columns: []
Using target column: Target
Feature matrix shape: (450798, 5)
Target distribution:
 Target
0    276227
1    174571
Name: count, dtype: int64


In [4]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42, stratify=y if y.nunique()>1 else None
)

print('Train shape:', X_train.shape)
print('Test shape:', X_test.shape)

Train shape: (315558, 5)
Test shape: (135240, 5)


In [3]:
# Import required libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
iris = load_iris()
X = iris.data      # features
y = iris.target    # labels

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Initialize SVM classifiers (linear and RBF)
svm_linear = SVC(kernel='linear', C=1.0, random_state=42)
svm_rbf = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)

# Fit models
svm_linear.fit(X_train, y_train)
svm_rbf.fit(X_train, y_train)

# Predictions
y_pred_lin = svm_linear.predict(X_test)
y_pred_rbf = svm_rbf.predict(X_test)

# Evaluation
print('Linear SVM Accuracy:', accuracy_score(y_test, y_pred_lin))
print('\nLinear SVM Classification Report:\n', classification_report(y_test, y_pred_lin))
print('\nLinear SVM Confusion Matrix:\n', confusion_matrix(y_test, y_pred_lin))

print('\nRBF SVM Accuracy:', accuracy_score(y_test, y_pred_rbf))
print('\nRBF SVM Classification Report:\n', classification_report(y_test, y_pred_rbf))
print('\nRBF SVM Confusion Matrix:\n', confusion_matrix(y_test, y_pred_rbf))


Linear SVM Accuracy: 1.0

Linear SVM Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Linear SVM Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

RBF SVM Accuracy: 1.0

RBF SVM Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


RBF SVM Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 